### ISSUE TITLE
How to connect to blockchain?

### ISSUE THREAD

**Issue by prassanapilankar5** [simonmok/blockchain-certificate#1]
Can you please tell me how to connect this project with blockchain?? this gonna help me alot ,can you please tell me?

**Comment by simonmok** [comment]
Hello, it is as simple as first running node_modules/.bin/ganache-cli, before you run "npm run dev".

**Comment by prassanapilankar5** [comment]
I really appreciate thay you've replied, 
I just clone this repo
Can you tell me step wise how to run?
I tried truffle developed & migrate & then running nom run dev it gives error , blockchain not connected

**Comment by prassanapilankar5** [comment]
Got it bro,thank you so much

**Comment by simonmok** [comment]
You are most welcome. I have updated README.md on the steps to get the apps running.

Meanwhile, I have updated the CDN link of web3 library that has gone outdated. Please check out the latest commit.  Have a good day!

**Comment by prassanapilankar5** [comment]
something is going wrong,can you mail me detailed step wise procedure?am trying to add new student into list but its not upadting, prassanapilankar5@gmail.com

**Comment by prassanapilankar5** [comment]
Run deploy-contract.js to create some initial testing data.


how to perform this step?
i know am may be annoying you ,am really soryy for that but am new developer not able to find proper ways .it will be very helpfull

**Comment by simonmok** [comment]
No worries. You need to install node, then run "node deploy-contract.js"

**Comment by prassanapilankar5** [comment]
thank you so much for helping me out
