### ISSUE TITLE
Address not found

### ISSUE THREAD

**Issue by bigyanpaudel** [simonmok/blockchain-certificate#2]
Hello sir,

after running the app it says then if i was to issue a certificate it would say address not found. in the account address option i put one of the address provided in the ganache cli.

**Comment by simonmok** [comment]
Users are identified by unique address so you should put account address generated by ganache.
If the address is not recognized, it says Address not Found which is an expected outcome.
Hope it clarifies.

**Comment by bigyanpaudel** [comment]
Yes sir it tells Address not found! 
How do you solve that? Can I please reach you on facebook or anywhere instead because I have so many questions to ask to you and this is so slower.

**Comment by simonmok** [comment]
Hi, as mentioned, you need to provide a valid address.

So here is the way.
Let's say you get this from ganache. 

Available Accounts
==================
(0) 0xa806565df7fc7f07fa82d081905384b31d063c96 (~100 ETH)
(1) 0x90b1a45eaadd7352583ed72d40a75da9a5a93b07 (~100 ETH)
(2) 0xb9033d9975889ea8c299834e53bba31f0956a1a5 (~100 ETH)
(3) 0xcbd8ad66c88b440d02a071c36f0f3fabbf2c638f (~100 ETH)
(4) 0x4dd27e8123e56f5d50997183ee903e814325dfea (~100 ETH)
(5) 0x30f2c589527ac44b2e1de77d8818be69c6d41ce4 (~100 ETH)
(6) 0x9bfde85d78e4aa739ec0078dd6e0890f1cdebcd9 (~100 ETH)
(7) 0xa407bb3e263bebe4f9808d445ae175d81266a3a1 (~100 ETH)
(8) 0x7f0b8f407807022cc4bd5d6f76ce8e20828a5e71 (~100 ETH)
(9) 0xbfacfa271bf7ec9d5bf5ccda217bc884331b0cc5 (~100 ETH)

From my codes, the student account is the account listed in (2). So under http://localhost/certificate.html, copy and paste the student account address as 0xb9033d9975889ea8c299834e53bba31f0956a1a5. Fill in the rest of form as well.
Submit and you will see it saved to blockchain.

**Comment by bigyanpaudel** [comment]
I tried this way many times and as you can see on the attached screenshots, even if the address is same as in the code of issuer that is ethaccounts[0] its still says account address not found. I have added screenshots as well.

**Comment by bigyanpaudel** [comment]
Also is there a documentation or some paper you referred to while doing this project? 
It's because I found this project very fascinating and decided to submit it as my final project and hence I have to prepare a very long report about this and I would be needing informations on technology stack and project flow etc. 

And If you could help me with that, I would be really really thankful.

**Comment by simonmok** [comment]
Hi,
From your screenshot, you are now at another page to register a new certificate issuer. For this case, refrain from using the first 3 accounts which are already in use if you have run deploy-contract.js.

As to your second question, it is not based on any paper, unless I am writing mine. You can give me a credit in your report. Good luck!

**Comment by bigyanpaudel** [comment]
Hello sir, 
Still the same issue. This time i used the fourth address and still the same problem exists. 

Also, i need some thing like the technology stack you used and also the process of the app such as first you register and then you issue as such. If you would do that that would be really really helpful and much better if you had a documentation of this report instead. Ofcourse I will give all my credits to you in the report. :)

![issuer2](https://user-images.githubusercontent.com/34052482/84416608-2955ff00-ac34-11ea-8c7a-87126c45519a.png)
![address2](https://user-images.githubusercontent.com/34052482/84416598-278c3b80-ac34-11ea-8a5f-b6b6af9ec9c9.png)

**Comment by bigyanpaudel** [comment]
SOLVED!!!

So basically the problem was the capital letters on the adress and making it all small letters solved it sir. :)
![issuersuccess](https://user-images.githubusercontent.com/34052482/84418881-856e5280-ac37-11ea-8d1d-cb7d7c347bac.png)
